name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Build with Maven
        run: |
          mvn --batch-mode clean package -PbuildKar
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nexus-repository-ansiblegalaxy/target/*.jar
            nexus-repository-ansiblegalaxy/target/*.kar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}